[providers]
python = "3.11"
node = "18"

[variables]
NODE_ENV = "production"

[phases.build]
dependsOn = ["setup"]
cmds = [
  "cd backend && pip install -r requirements.txt", 
  "cd frontend && npm install", 
  "cd frontend && npm run build",
  "mkdir -p backend/static",
  "cp -r frontend/build/* backend/static/"
]

[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "npm"]

[start]
cmd = "cd backend && python server.py"